name: "Update Changelog"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit & Push
        run: |
          set +e

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -b chore/update-changelog
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push -u origin chore/update-changelog

      - name: Create PR
        run: |
          gh pr create \
            --title "chore: update readme" \
            --label docs,automated

          gh pr merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
