name: Docker Compose Deployment

on:
  push:
    branches:
      - feat/minimum-bot

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_PRIVATE }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        run: |
          docker compose up -d --remove-orphans
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
